using UnityEngine;

public class SceneData : MonoBehaviour
{
    [SerializeField] private PlayerController _player;
    [Header("Field")]
    [SerializeField] private GameObject _cellPrefab;
    [SerializeField] private Transform _fieldTransform;
    [SerializeField] private GameObject _blueCircle;
    [SerializeField] private GameObject _redCircle;
    [SerializeField] private Transform _dotsTransform;
    [SerializeField] private Transform _pointer;
    [SerializeField] private Transform _blueCirclePhantom;
    [SerializeField] private Transform _redCirclePhantom;
    [Header("Environment")]
    [SerializeField] private GameObject _blueLine;
    [SerializeField] private GameObject _redLine;
    [SerializeField] private Transform _lines;
    [SerializeField] private GameObject _surround;
    [SerializeField] private Material _blueMaterial;
    [SerializeField] private Material _redMaterial;
    [SerializeField] private Transform _surrounds;
    [SerializeField] private Transform _symbols;
    [SerializeField] private Transform _secTrees;
    [Header("Score")]
    [SerializeField] private GameObject _player1Name;
    [SerializeField] private GameObject _player1Points;
    [SerializeField] private GameObject _player1Timer;
    [SerializeField] private GameObject _player2Name;
    [SerializeField] private GameObject _player2Points;
    [SerializeField] private GameObject _player2Timer;
    [Header("Buttons")]
    [SerializeField] private GameObject _roomButton;
    [SerializeField] private GameObject _toolsButton;
    [SerializeField] private GameObject _settingsButton;
    [Header("Markers")]
    [SerializeField] private GameObject _blueMarker;
    [SerializeField] private GameObject _redMarker;
    [SerializeField] private GameObject _blueCircleLock;
    [SerializeField] private GameObject _redCircleLock;
    [Header("Rewind")]
    [SerializeField] private GameObject _leftFast;
    [SerializeField] private GameObject _leftButton;
    [SerializeField] private GameObject _rightButton;
    [SerializeField] private GameObject _rightFast;
    [SerializeField] private GameObject _rightAuto;
    [Header("Tree")]
    [SerializeField] private GameObject _blueCircleTree;
    [SerializeField] private GameObject _redCircleTree;
    [SerializeField] private Transform _mainTree;
    [Header("Chat")]
    [SerializeField] private GameObject _messagePrefab;
    [SerializeField] private GameObject _chat;
    [SerializeField] private GameObject _chatButton;
    [SerializeField] private GameObject _commentPrefab;
    [SerializeField] private GameObject _comments;
    [SerializeField] private GameObject _commentButton;
    [SerializeField] private GameObject _players;
    [SerializeField] private GameObject _playerButton;
    [SerializeField] private GameObject _inputField;
    [SerializeField] private GameObject _sendButton;
    [Header("Panels")]
    [SerializeField] private GameObject _darkPanel;
    [SerializeField] private GameObject _waitingPanel;
    [SerializeField] private GameObject _roomPanel;
    [SerializeField] private GameObject _toolsPanel;
    [SerializeField] private GameObject _settingsPanel;
    [SerializeField] private GameObject _infoPanel;
    [Header("Room")]
    [SerializeField] private GameObject _roomPrefab;
    [SerializeField] private Transform _listRooms;
    [SerializeField] private GameObject _namePrefab;
    [SerializeField] private Transform _listNames;
    [Header("Tools")]
    [SerializeField] private GameObject _widthInput;
    [SerializeField] private GameObject _heightInput;
    [SerializeField] private GameObject _field;
    [SerializeField] private GameObject _bigDotToggle;
    [SerializeField] private GameObject _mediumDotToggle;
    [SerializeField] private GameObject _smallDotToggle;
    [SerializeField] private GameObject _dots;
    [SerializeField] private GameObject _blueRedDots;
    [SerializeField] private GameObject _blueDot;
    [SerializeField] private GameObject _redDot;
    [SerializeField] private GameObject _num;
    [SerializeField] private GameObject _cross;
    [SerializeField] private GameObject _line;
    [SerializeField] private GameObject _arrow;
    [SerializeField] private GameObject _brush;
    [SerializeField] private GameObject _eraser;
    [Header("Settings")]
    [SerializeField] private GameObject _newParty;
    [SerializeField] private GameObject _roomsList;
    [SerializeField] private GameObject _noCrossToggle;
    [SerializeField] private GameObject _cross1Toggle;
    [SerializeField] private GameObject _cross4Toggle;
    [SerializeField] private GameObject _pointerToggle;
    [SerializeField] private GameObject _gameButton;
    [SerializeField] private GameObject _coachGroup;
    [SerializeField] private GameObject _uploadButton;
    [SerializeField] private GameObject _saveButton;
    [SerializeField] private GameObject _applyButton;
    [SerializeField] private GameObject _infoButton;
    [SerializeField] private GameObject _leaveButton;
    [SerializeField] private GameObject _closeSettings;
    [SerializeField] private GameObject _closeInfo;

    public PlayerController Player => _player;
    public GameObject CellPrefab => _cellPrefab;
    public Transform FieldTransform => _fieldTransform;
    public GameObject BlueCircle => _blueCircle;
    public GameObject RedCircle => _redCircle;
    public Transform DotsTransform => _dotsTransform;
    public Transform Pointer => _pointer;
    public Transform BlueCirclePhantom => _blueCirclePhantom;
    public Transform RedCirclePhantom => _redCirclePhantom;
    public GameObject BlueLine => _blueLine;
    public GameObject RedLine => _redLine;
    public Transform Lines => _lines;
    public GameObject Surround => _surround;
    public Material BlueMaterial => _blueMaterial;
    public Material RedMaterial => _redMaterial;
    public Transform Surrounds => _surrounds;
    public Transform Symbols => _symbols;
    public Transform SecTrees => _secTrees;
    public GameObject Player1Name => _player1Name;
    public GameObject Player1Points => _player1Points;
    public GameObject Player1Timer => _player1Timer;
    public GameObject Player2Name => _player2Name;
    public GameObject Player2Points => _player2Points;
    public GameObject Player2Timer => _player2Timer;
    public GameObject RoomButton => _roomButton;
    public GameObject ToolsButton => _toolsButton;
    public GameObject SettingsButton => _settingsButton;
    public GameObject BlueMarker => _blueMarker;
    public GameObject RedMarker => _redMarker;
    public GameObject BlueCircleLock => _blueCircleLock;
    public GameObject RedCircleLock => _redCircleLock;
    public GameObject LeftFast => _leftFast;
    public GameObject LeftButton => _leftButton;
    public GameObject RightButton => _rightButton;
    public GameObject RightFast => _rightFast;
    public GameObject RightAuto => _rightAuto;
    public GameObject BlueCircleTree => _blueCircleTree;
    public GameObject RedCircleTree => _redCircleTree;
    public Transform MainTree => _mainTree;
    public GameObject MessagePrefab => _messagePrefab;
    public GameObject Chat => _chat;
    public GameObject ChatButton => _chatButton;
    public GameObject CommentPrefab => _commentPrefab;
    public GameObject Comments => _comments;
    public GameObject CommentButton => _commentButton;
    public GameObject Players => _players;
    public GameObject PlayerButton => _playerButton;
    public GameObject InputField => _inputField;
    public GameObject SendButton => _sendButton;
    public GameObject DarkPanel => _darkPanel;
    public GameObject WaitingPanel => _waitingPanel;
    public GameObject RoomPanel => _roomPanel;
    public GameObject ToolsPanel => _toolsPanel;
    public GameObject SettingsPanel => _settingsPanel;
    public GameObject InfoPanel => _infoPanel;
    public GameObject RoomPrefab => _roomPrefab;
    public Transform ListRooms => _listRooms;
    public GameObject NamePrefab => _namePrefab;
    public Transform ListNames => _listNames;
    public GameObject WidthInput => _widthInput;
    public GameObject HeightInput => _heightInput;
    public GameObject Field => _field;
    public GameObject BigDotToggle => _bigDotToggle;
    public GameObject MediumDotToggle => _mediumDotToggle;
    public GameObject SmallDotToggle => _smallDotToggle;
    public GameObject Dots => _dots;
    public GameObject BlueRedDots => _blueRedDots;
    public GameObject BlueDot => _blueDot;
    public GameObject RedDot => _redDot;
    public GameObject Num => _num;
    public GameObject Cross => _cross;
    public GameObject Line => _line;
    public GameObject Arrow => _arrow;
    public GameObject Brush => _brush;
    public GameObject Eraser => _eraser;
    public GameObject NewParty => _newParty;
    public GameObject RoomsList => _roomsList;
    public GameObject NoCrossToggle => _noCrossToggle;
    public GameObject Cross1Toggle => _cross1Toggle;
    public GameObject Cross4Toggle => _cross4Toggle;
    public GameObject PointerToggle => _pointerToggle;
    public GameObject GameButton => _gameButton;
    public GameObject CoachGroup => _coachGroup;
    public GameObject UploadButton => _uploadButton;
    public GameObject SaveButton => _saveButton;
    public GameObject ApplyButton => _applyButton;
    public GameObject InfoButton => _infoButton;
    public GameObject LeaveButton => _leaveButton;
    public GameObject CloseSettings => _closeSettings;
    public GameObject CloseInfo => _closeInfo;
}
